### ISSUE TITLE
how can I see all of the figures in one page?

### ISSUE THREAD

**Issue by liamxg** [npechl/TidyTuesday#1]
Dear @npechl,

I like your figures, how can I see all of the figures in one page?
Thanks.

**Comment by npechl** [comment]
Hi @liamxg,

Thanks for your comment! During the next days, I'll be working and updating my personal [GitHub page](https://npechl.github.io/) to include most of the graphs. In the meantime, you can find all my figures on my [Twitter account](https://twitter.com/npechl/media).

Regards,
Nikos

**Comment by liamxg** [comment]
Dear @npechl,

Cool! Thanks.
